version: "3.8"

services:

  accounts:
    image: mohdamerkhan786/accounts:latest
    mem_limit: 700m
    ports:
      - "8081:8081"
    networks:
      - mohdamerkhan786-network
    
  loans:
    image: mohdamerkhan786/loans:latest
    mem_limit: 700m
    ports:
      - "8082:8082"
    networks:
      - mohdamerkhan786-network
    
  cards:
    image: mohdamerkhan786/cards:latest
    mem_limit: 700m
    ports:
      - "8083:8083"
    networks:
      - mohdamerkhan786-network
    
networks:
  mohdamerkhan786-network: