version: "3.8"

services:

  configserver:
    image: mohdamerkhan786/configserver:latest
    mem_limit: 700m
    ports:
      - "8888:8888"
    networks:
     - mohdamerkhan786
   
  eurekaserver:
    image: mohdamerkhan786/eurekaserver:latest
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
     - mohdamerkhan786
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8888/
      
  accounts:
    image: mohdamerkhan786/accounts:latest
    mem_limit: 700m
    ports:
      - "8081:8081"
    networks:
      - mohdamerkhan786
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8888/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
  
  loans:
    image: mohdamerkhan786/loans:latest
    mem_limit: 700m
    ports:
      - "8082:8082"
    networks:
      - mohdamerkhan786
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8888/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
    
  cards:
    image: mohdamerkhan786/cards:latest
    mem_limit: 700m
    ports:
      - "8083:8083"
    networks:
      - mohdamerkhan786
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8888/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
      
networks:
  mohdamerkhan786: